server:
  port: 8889
  servlet:
    context-path: /quiz

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./quizmini.db
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: i18n.index, i18n.manage, i18n.card
    encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl