server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:quizmini.db
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML